# Generated by Django 3.1.7 on 2021-03-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userPortal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership_form",
            name="is_approved",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="is_approved"
            ),
        ),
    ]
