# Generated by Django 3.1.7 on 2021-03-25 05:07

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partyPage", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("compPage", "0001_initial"),
        ("coursePage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_time",
                    models.TimeField(max_length=10, verbose_name="from_time"),
                ),
                ("to_time", models.TimeField(max_length=10, verbose_name="to_time")),
                ("date", models.DateField(max_length=20, verbose_name="date")),
                (
                    "rem_num_participants",
                    models.IntegerField(default=0, verbose_name="rem_num_participants"),
                ),
                (
                    "max_num_participants",
                    models.IntegerField(
                        default=50, verbose_name="max_num_participants"
                    ),
                ),
                (
                    "competition",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="compPage.competition",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coursePage.course",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partyPage.event",
                    ),
                ),
                (
                    "game",
                    models.ManyToManyField(
                        blank=True, default=None, to="compPage.Game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NON-MEMBER", "Non-Member"),
                            ("MEMBER", "Member"),
                            ("COORDINATOR", "Coordinator"),
                            ("COMMITTEE", "Committee"),
                            ("MANAGER", "Manager"),
                        ],
                        default="NON-MEMBER",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                ("age", models.DateField(verbose_name="age")),
                ("gender", models.CharField(max_length=10, verbose_name="gender")),
                ("course", models.ManyToManyField(to="coursePage.Course")),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partyPage.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mysite.newuser",),
            managers=[
                ("objects", mysite.models.CommitteeManager()),
            ],
        ),
        migrations.CreateModel(
            name="Coordinator",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mysite.newuser",),
            managers=[
                ("objects", mysite.models.CoordinatorManager()),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mysite.newuser",),
            managers=[
                ("objects", mysite.models.ManagerManager()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mysite.newuser",),
            managers=[
                ("objects", mysite.models.MemberManager()),
            ],
        ),
    ]
