# Generated by Django 3.1.7 on 2021-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Only Males are allowed"),
                    ("Female", "Only Females are allowed"),
                    ("Both", "Everybody is allowed"),
                ],
                default="Both",
                max_length=10,
                verbose_name="gender",
            ),
        ),
    ]
