# Generated by Django 3.1.2 on 2021-03-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_auto_20210325_0920"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="membership_date",
            field=models.DateField(
                default="2001-01-01", verbose_name="membership_date"
            ),
        ),
    ]
