# Generated by Django 3.1.2 on 2021-03-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0005_auto_20210325_1425"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compslot",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mysite.slot",),
        ),
        migrations.CreateModel(
            name="Courseslot",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mysite.slot",),
        ),
        migrations.CreateModel(
            name="Eventslot",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mysite.slot",),
        ),
        migrations.CreateModel(
            name="Gameslot",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mysite.slot",),
        ),
        migrations.CreateModel(
            name="Memberslot",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mysite.slot",),
        ),
        migrations.AddField(
            model_name="slot",
            name="day",
            field=models.CharField(max_length=20, null=True, verbose_name="day"),
        ),
    ]
