# Generated by Django 3.1.2 on 2021-03-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0006_auto_20210325_1741"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slot",
            old_name="date",
            new_name="Date",
        ),
        migrations.RenameField(
            model_name="slot",
            old_name="day",
            new_name="Day",
        ),
    ]
