# Generated by Django 3.1.7 on 2021-03-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0008_auto_20210326_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="aCardNum",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="acard_num"
            ),
        ),
    ]
