# Generated by Django 3.1.7 on 2021-03-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursePage", "0002_auto_20210327_1212"),
        ("mysite", "0014_auto_20210327_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="course",
            field=models.ManyToManyField(blank=True, to="coursePage.Course"),
        ),
    ]
