# Generated by Django 3.1.7 on 2021-03-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0015_auto_20210328_1831"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "head",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "Description",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("url", models.URLField(blank=True, default="#", null=True)),
                ("users", models.ManyToManyField(to="mysite.NewUser")),
            ],
        ),
    ]
