# Generated by Django 3.1.7 on 2021-03-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0016_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="cert",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="cert"
            ),
        ),
        migrations.AddField(
            model_name="newuser",
            name="comp_cert",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="comp_cert"
            ),
        ),
    ]
