# Generated by Django 3.1.7 on 2021-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0017_auto_20210329_2231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="users",
            field=models.ManyToManyField(blank=True, to="mysite.NewUser"),
        ),
    ]
