# Generated by Django 3.1.7 on 2021-04-04 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "from_age",
                    models.IntegerField(blank=True, null=True, verbose_name="from_age"),
                ),
                (
                    "to_age",
                    models.IntegerField(blank=True, null=True, verbose_name="to_age"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_age", models.IntegerField(default=12, verbose_name="from_age")),
                ("to_age", models.IntegerField(default=32, verbose_name="to_age")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Only Males are allowed"),
                            ("Female", "Only Females are allowed"),
                            ("Both", "Everybody is allowed"),
                        ],
                        default="Both",
                        max_length=10,
                        verbose_name="gender",
                    ),
                ),
                ("game_type", models.CharField(max_length=100, verbose_name="type")),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_tickets",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(4)],
                        verbose_name="num_tickets",
                    ),
                ),
                ("competition", models.ManyToManyField(to="compPage.Competition")),
            ],
        ),
    ]
