# Generated by Django 3.1.2 on 2021-03-26 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compPage", "0002_auto_20210325_1037"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="games",
        ),
        migrations.AddField(
            model_name="game",
            name="competition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compPage.competition",
            ),
        ),
    ]
