# Generated by Django 3.1.7 on 2021-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mysite", "0001_initial"),
        ("compPage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="user",
            field=models.ManyToManyField(to="mysite.NewUser"),
        ),
        migrations.AddField(
            model_name="competition",
            name="games",
            field=models.ManyToManyField(to="compPage.Game"),
        ),
    ]
