# Generated by Django 3.1.7 on 2021-03-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compPage", "0003_auto_20210326_0859"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="from_age",
            field=models.IntegerField(blank=True, null=True, verbose_name="from_age"),
        ),
        migrations.AddField(
            model_name="competition",
            name="to_age",
            field=models.IntegerField(blank=True, null=True, verbose_name="to_age"),
        ),
    ]
