# Generated by Django 3.1.2 on 2021-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_newuser_membership_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="address",
            field=models.CharField(max_length=200, null=True, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="newuser",
            name="pincode",
            field=models.IntegerField(null=True, verbose_name="pincode"),
        ),
    ]
