# Generated by Django 3.1.7 on 2021-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0007_auto_20210326_0859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="Day",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="day"
            ),
        ),
    ]
