# Generated by Django 3.1.7 on 2021-03-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compPage", "0003_auto_20210326_0859"),
        ("mysite", "0010_newuser_comp_participated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="game",
        ),
        migrations.AddField(
            model_name="slot",
            name="game",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="compPage.game",
            ),
        ),
    ]
