# Generated by Django 3.1.7 on 2021-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0011_auto_20210326_1922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="rem_num_participants",
            field=models.IntegerField(default=50, verbose_name="rem_num_participants"),
        ),
    ]
