# Generated by Django 3.1.7 on 2021-03-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0012_auto_20210326_2206"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="users",
            field=models.ManyToManyField(to="mysite.NewUser"),
        ),
    ]
