# Generated by Django 3.1.2 on 2021-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0013_slot_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="is_committee",
            field=models.BooleanField(default="False", verbose_name="is_committee"),
        ),
        migrations.AddField(
            model_name="newuser",
            name="is_coordinator",
            field=models.BooleanField(default="False", verbose_name="is_coordinator"),
        ),
        migrations.AddField(
            model_name="newuser",
            name="is_member",
            field=models.BooleanField(default="False", verbose_name="is_member"),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="address"
            ),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="city",
            field=models.CharField(
                blank=True,
                default="Kharagpur",
                max_length=15,
                null=True,
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="country",
            field=models.CharField(
                blank=True,
                default="India",
                max_length=15,
                null=True,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="newuser",
            name="pincode",
            field=models.IntegerField(blank=True, null=True, verbose_name="pincode"),
        ),
    ]
