# Generated by Django 3.1.7 on 2021-04-04 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                (
                    "num_students",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="num_students",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default="True", verbose_name="is_active"),
                ),
                ("start_date", models.DateField(null=True, verbose_name="start_date")),
                ("last_date", models.DateField(null=True, verbose_name="last_date")),
                ("cost", models.IntegerField(null=True, verbose_name="cost")),
            ],
        ),
    ]
