# Generated by Django 3.1.2 on 2021-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursePage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default="False", verbose_name="is_active"),
        ),
        migrations.AddField(
            model_name="course",
            name="last_date",
            field=models.DateField(null=True, verbose_name="last_date"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(null=True, verbose_name="start_date"),
        ),
    ]
