# Generated by Django 3.1.7 on 2021-03-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursePage", "0002_auto_20210327_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="max_age",
            field=models.IntegerField(default=25, null=True, verbose_name="max_age"),
        ),
        migrations.AddField(
            model_name="course",
            name="min_age",
            field=models.IntegerField(default=10, null=True, verbose_name="min_age"),
        ),
    ]
