# Generated by Django 3.1.7 on 2021-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("text", models.CharField(max_length=500, verbose_name="text")),
                (
                    "reply",
                    models.CharField(
                        default="Thanks for your feedback",
                        max_length=500,
                        verbose_name="reply",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_manager", models.BooleanField(default=False)),
                (
                    "coordinators",
                    models.ManyToManyField(
                        blank=True, related_name="coordinators", to="mysite.Coordinator"
                    ),
                ),
                (
                    "member",
                    models.ManyToManyField(related_name="member", to="mysite.Member"),
                ),
                (
                    "nonmember",
                    models.ManyToManyField(
                        related_name="nonmember", to="mysite.NewUser"
                    ),
                ),
            ],
        ),
    ]
