# Generated by Django 3.1.7 on 2021-03-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mysite", "0007_auto_20210326_0859"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership_form",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "ACardNum",
                    models.CharField(
                        default="", max_length=20, null=True, verbose_name="aCardNum"
                    ),
                ),
                (
                    "num_months",
                    models.PositiveIntegerField(
                        default=1, null=True, verbose_name="num_months"
                    ),
                ),
                (
                    "cert",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="cert"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="is_approved"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.newuser",
                    ),
                ),
            ],
        ),
    ]
