# Generated by Django 3.1.7 on 2021-03-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userPortal", "0002_auto_20210327_2338"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership_form",
            name="reason",
            field=models.CharField(
                blank=True, default="", max_length=150, null=True, verbose_name="reason"
            ),
        ),
    ]
