# Generated by Django 3.1.7 on 2021-03-30 15:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("userPortal", "0004_membership_form_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership_form",
            name="phone_num",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="phone_num",
            ),
        ),
    ]
