# Generated by Django 3.1.7 on 2021-04-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="userid"
                    ),
                ),
                ("isBooked", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="EventBooking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_aadhar",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="acard_num"
                    ),
                ),
                ("Date", models.DateField(verbose_name="date")),
                ("from_time", models.TimeField(verbose_name="from_time")),
                ("to_time", models.TimeField(verbose_name="to_time")),
            ],
        ),
    ]
